

- name: Update APT packages
  become: yes
  apt:
    update_cache: true

- name: remove dependencies that are no longer required
  apt:
    autoremove: yes

- name: Install Python
  become: yes
  apt:
    name: python3
    state: latest
    update_cache: yes

- name: Install NodeJs
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: Install pm2
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present